### ISSUE TITLE
Is this a bridge or a client?

### ISSUE THREAD

**Issue by luxus** [jandebeule/nukiPyBridge#12]
Hi,
I'm a little bit confused by the information in the read me. Is this a software bridge or just a client?
My old android device just droped from the wall and need a new bridge..

**Comment by jandebeule** [comment]
It's not really a bridge as it does not provide a web/rest api.
It's more a python lib that you can use to control your nuki. It's up to the user to extend this anyway you want and for instance create a bridge from it.
