### ISSUE TITLE
newStateAvailable returns -1

### ISSUE THREAD

**Issue by federic0** [jandebeule/nukiPyBridge#6]
Hi,

Many times, isNewNukiStateAvailable is returning a value of -1 (without printing any errors)

Do you know why that is?

thanks

**Comment by jandebeule** [comment]
This should only happen if you don't receive BLE beacons from your Nuki device or the beacons received are not formatted correctly. 
I did not see this behavior before. I'll try to add some debug statements soon to see what you receive.

**Comment by federic0** [comment]
Thanks for the quick reply, I thought too that it may be a bluetooth problem on my machine (or on the Nuki). I will try to use another bluetooth card to see if the behaviour changes. I did notice too that the latest nuki App has a new "energy-saving mode" configuration that affects the interval in which the lock communicates the Nuki App, do you know if this has any impact on your bridge?

**Comment by jandebeule** [comment]
Could you try again now? I've added some additional debug statements.
Please send me the log from the console to investigate.

energy-saving mode does not seem to have impact on the bridge from my observations, but I'll check which configuration is currently applied on my lock at home

**Comment by federic0** [comment]
Here's the output:

```
isNewNukiStateAvailable() -> search through 9 received beacons...
non-Nuki beacon found: mac=2d:9d:10:ae:23:28, signature=23ae109d2d0f02011b0bff4c00090603
non-Nuki beacon found: mac=2d:9d:10:ae:23:28, signature=23ae109d2d0f02011b0bff4c00090603
non-Nuki beacon found: mac=04:4b:ed:a2:4a:ba, signature=ba4aa2ed4b040e02011a0aff4c001005
non-Nuki beacon found: mac=54:d2:72:ea:39:61, signature=a92ee200550111e4916c0800200c9a66
non-Nuki beacon found: mac=2d:9d:10:ae:23:28, signature=23ae109d2d0f02011b0bff4c00090603
non-Nuki beacon found: mac=04:4b:ed:a2:4a:ba, signature=ba4aa2ed4b040e02011a0aff4c001005
non-Nuki beacon found: mac=04:4b:ed:a2:4a:ba, signature=ba4aa2ed4b040e02011a0aff4c001005
non-Nuki beacon found: mac=2d:9d:10:ae:23:28, signature=23ae109d2d0f02011b0bff4c00090603
non-Nuki beacon found: mac=04:4b:ed:a2:4a:ba, signature=ba4aa2ed4b040e02011a0aff4c001005
isNewNukiStateAvailable() -> result=-1
New state available: -1
```

**Comment by federic0** [comment]
I've added another BT adapter and tried with it, but keep having the same issue. I can control the lock (lock and unlock) but cannot read if a new state is available...

```
hcitool lescan             
LE Scan ...
2D:9D:10:AE:23:28 (unknown)
54:D2:72:EA:39:61 (unknown)
54:D2:72:EA:39:61 Nuki_05EA3961
04:4B:ED:A2:4A:BA (unknown)
04:4B:ED:A2:4A:BA (unknown)
```

```
python nukiNewStateCheck.py
isNewNukiStateAvailable() -> search through 9 received beacons...
non-Nuki beacon found: mac=04:4b:ed:a2:4a:ba, signature=ba4aa2ed4b040e02011a0aff4c001005
non-Nuki beacon found: mac=2d:9d:10:ae:23:28, signature=23ae109d2d0f02011b0bff4c00090603
non-Nuki beacon found: mac=54:d2:72:ea:39:61, signature=a92ee200550111e4916c0800200c9a66
non-Nuki beacon found: mac=54:d2:72:ea:39:61, signature=39ea72d2540f0e094e756b695f303545
non-Nuki beacon found: mac=04:4b:ed:a2:4a:ba, signature=ba4aa2ed4b040e02011a0aff4c001005
non-Nuki beacon found: mac=2d:9d:10:ae:23:28, signature=23ae109d2d0f02011b0bff4c00090603
non-Nuki beacon found: mac=04:4b:ed:a2:4a:ba, signature=ba4aa2ed4b040e02011a0aff4c001005
non-Nuki beacon found: mac=2d:9d:10:ae:23:28, signature=23ae109d2d0f02011b0bff4c00090603
non-Nuki beacon found: mac=54:d2:72:ea:39:61, signature=a92ee200550111e4916c0800200c9a66
isNewNukiStateAvailable() -> result=-1
New state available: -1
```

**Comment by federic0** [comment]
Ok, found this: I guess at some point I had changed line 57 to:
`if beaconElements[0] == self.macAddress.lower() and beaconElements[1] == "a92ee200550111e4916c0800200c9a66":`
Making the mac address to lowercase was required for me, at some point I must have overwritten the file with the original and thus was getting the result shown above.
It's working fine now.
